clear
echo ''
echo '##################################################################'
echo ''
echo '\tWelcome to Malaco command line interface.'
echo ''
echo '##################################################################'
echo ''
echo ''
figlet -f roman -w 150 'malaco'
echo ''
echo ''
echo '##################################################################'
echo ''
echo '\tMalaco v.0.2.3 (beta) released under MIT license.'
echo ''
echo '##################################################################'
echo ''
echo ''
echo ''
echo ''
echo ''
echo ''
echo ''
echo ''
echo ''
echo ''
echo ''
echo ''
echo ''
