clear
echo ''
echo '##################################################################'
echo ''
echo '\tWelcome to Malaco command line interface.'
echo ''
echo '##################################################################'
echo ''
figlet -f roman -w 150 'malaco'
echo 'Usage'
echo '\t$ help - show help'
echo '\t$ status - get subway operational status'
echo '\t$ import - import data to output mechanism'
echo '\t$ connect - compile assets and startup local server'
echo '\t$ serve - serve port 9000 through ngrok'
echo ''
echo '##################################################################'
echo ''
