clear
echo ''
echo '##################################################################'
echo ''
echo '\tWelcome to Malaco command line interface.'
echo ''
echo '##################################################################'
echo ''
figlet -f roman -w 150 'malaco'
echo 'Usage'
echo '\tλ help\t\tshow help'
echo '\tλ status\tget subway operational status'
echo '\tλ import\timport data to output mechanism'
echo '\tλ connect\tcompile assets and startup local server'
echo '\tλ serve\t\tserve port 9000 through ngrok'
echo '\tλ refresh\tforce data to be updated'
echo ''
echo '##################################################################'
echo ''
